{"cve": {"id": "CVE-2024-53432", "sourceIdentifier": "cve@mitre.org", "published": "2024-11-21T18:15:14.420", "lastModified": "2024-11-21T18:15:14.420", "vulnStatus": "Received", "descriptions": [{"lang": "en", "value": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files."}], "metrics": {}, "references": [{"url": "https://github.com/PointCloudLibrary/pcl/issues/6162", "source": "cve@mitre.org"}]}}